[package]
name = "Magazines"
version = "0.0.1"
edition = "2024"

[dependencies]
axum = "0.8.3"
http = "1.3.1"
reqwest = { version = "0.12.22", default-features = false, features = ["json", "rustls-tls", "charset", "http2"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.0", features = ["full"] }
tower = "0.5.2"
tower-http = { version = "0.6.1", features = ["fs"] }
