name: Update Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Query refresh api
        env:
          TOKEN: ${{ secrets.FRONTEND_TOKEN }}
          ENDPOINT: ${{ secrets.FRONTEND_ENDPOINT }}
        run: |
          curl --request GET \
          --url $ENDPOINT \
          --header "Authorization: Bearer $TOKEN"
